### ISSUE TITLE
Thêm lựa chọn bắt đầu tải từ chap bao nhiêu.

### ISSUE THREAD

**Issue by Hyminem** [nguyentd01/metruyencv_downloader#1]
Tải hơn 400chap đã crash app rồi. Tôi nghĩ là nên thêm lựa chọn tải từng phần. vd từ 1-200 xong từ 200-400

**Comment by nguyentd01** [comment]
ok bro để tôi add

**Comment by nguyentd01** [comment]
ngoài ra bro có còn biết web truyện chữ hay light novel nào phổ biến không? nếu được thì tôi update thêm

**Comment by Hyminem** [comment]
> ngoài ra bro có còn biết web truyện chữ hay light novel nào phổ biến không? nếu được thì tôi update thêm

metruyencv là nhiều nhất rồi ông ạ, chỉ sau truyenyy nhưng truyenyy mất phí nên cũng khó tải. Với cả tôi nghĩ ông nên chỉnh ổ D sang ổ C vì một số người không sử dụng ổ D thì app lại crash

**Comment by nguyentd01** [comment]
Tôi cũng định cho thêm tùy chọn 
tùy chọn ổ .Mà tôi cũng vừa fix lỗi crash xong r ông test trên máy ông xem ổn chưa

**Comment by Hyminem** [comment]
> Tôi cũng định cho thêm tùy chọn tùy chọn ổ .Mà tôi cũng vừa fix lỗi crash xong r ông test trên máy ông xem ổn chưa

crash thì không nhưng mà có hai vấn đề là:
- epub được tạo xong thì không dùng ngay được trên Ios mà phải convert lại
- cái table of contents thì đánh dấu linh tinh: kiểu 1 101 102 2 201 -> ông chỉnh lại cho nó đánh số thành 0001, 0002 là ok

**Comment by Hyminem** [comment]
> ngoài ra bro có còn biết web truyện chữ hay light novel nào phổ biến không? nếu được thì tôi update thêm

tối mới tìm được web truyenchu.vn cũng update truyện thường xuyên đấy

**Comment by Hyminem** [comment]
tối mới tìm được web truyenchu.vn cũng update truyện thường xuyên đấy

**Comment by kien202089** [comment]
lỗi đánh số thứ tự chương bạn ơi

**Comment by yeuemhon** [comment]
> ngoài ra bro có còn biết web truyện chữ hay light novel nào phổ biến không? nếu được thì tôi update thêm

Anh thử trang ztruyen.vn cũng thường cập nhật á...
