### ISSUE TITLE
Sao file exe download lỗi

### ISSUE THREAD

**Issue by Gum97** [nguyentd01/metruyencv_downloader#2]
Chào ad có vài feedback sau ad xem xét giúp ạ.
File exe đang lỗi nhập link, nhập số chương là lỗi không download được.
Ngoài ra đang phải nhập tay số chương có thể tuỳ chọn tải hết hoặc nhập tay nếu muốn không?

**Comment by kien202089** [comment]
tải đánh dấu chương bị lẫn lộn hết bạn ơi

**Comment by nguyentd01** [comment]
ok để mình fix lại

**Comment by huy270985** [comment]
Tải chương bị lỗi thứ tự 1->10->11->12, với lại có nhiều chương bị lỗi chỉ tải 1-2 đoạn thì qua chương sau, đối với những chương lỗi, mình tải lại 1 chương vẫn bị tình trạng này.

**Comment by nguyentd01** [comment]
Mình vừa fix lỗi sắp chương r á.B test thử đi

**Comment by duxonem** [comment]
Metruyencv có những đoạn nó đổi thành hình ảnh cho nên không thể chỉ get text là đủ đâu

**Comment by duxonem** [comment]
Đây là function lấy nội dung chương truyện bị đổi thành hình ảnh

async function getChapterContent() {
    await sleep(100);
    await waitForKeyElement('#load-more', 3000, 'innerText');
    await sleep(300); //cho chac an
 
    let canvas = document.querySelectorAll('#chapter-detail canvas');
    if (canvas.length > 0) {
        const scheduler = await Tesseract.createScheduler();
        let workers = Array(navigator.hardwareConcurrency - 1);
 
        for (let i = 0; i < workers.length; i++) workers[i] = await Tesseract.createWorker('vie');
        workers = await Promise.all(workers.map((wk) => (scheduler.addWorker(wk))));
 
        let result = await Promise.all(Array.from(canvas).map((cv) => (scheduler.addJob('recognize', cv.toDataURL()))));
        result.forEach((e, i) => canvas[i].outerHTML = `<fromcanvas>${e.data.text}</fromcanvas>`);
 
        scheduler.terminate();
    }
 
    return document.querySelector('#chapter-detail')?.innerText;
}

**Comment by nguyentd01** [comment]
Thank bro. Để mình fix lại

**Comment by nguyentd01** [comment]
> Đây là function lấy nội dung chương truyện bị đổi thành hình ảnh
> 
> ```
> async function getChapterContent() {
>     await sleep(100);
>     await waitForKeyElement('#load-more', 3000, 'innerText');
>     await sleep(300); //cho chac an
>  
>     let canvas = document.querySelectorAll('#chapter-detail canvas');
>     if (canvas.length > 0) {
>         const scheduler = await Tesseract.createScheduler();
>         let workers = Array(navigator.hardwareConcurrency - 1);
>  
>         for (let i = 0; i < workers.length; i++) workers[i] = await Tesseract.createWorker('vie');
>         workers = await Promise.all(workers.map((wk) => (scheduler.addWorker(wk))));
>  
>         let result = await Promise.all(Array.from(canvas).map((cv) => (scheduler.addJob('recognize', cv.toDataURL()))));
>         result.forEach((e, i) => canvas[i].outerHTML = `<fromcanvas>${e.data.text}</fromcanvas>`);
>  
>         scheduler.terminate();
>     }
>  
>     return document.querySelector('#chapter-detail')?.innerText;
> }
> ```

Thật ra mình không cần dùng orc mà chỉ cần tải lại trang web là được :)))).Nhanh gọn hơn
