### ISSUE TITLE
1.0.2 và 1.0.3

### ISSUE THREAD

**Issue by yeuemhon** [nguyentd01/metruyencv_downloader#3]
Anh ơi, sao 1.0.2 thì copy đủ chương mà có nhiều chương thiếu nội dung còn 1.0.3 thì copy đủ nội dung nhưng lại thiếu chương....

**Comment by nguyentd01** [comment]
à cái này là do có 1 vài chap bị chặn vì chưa đăng nhập hoặc không load được á.Mình đang làm 1 bản cập nhật lớn có đăng nhập để fix lỗi thiếu chương này

**Comment by yeuemhon** [comment]
> à cái này là do có 1 vài chap bị chặn vì chưa đăng nhập hoặc không load được á.Mình đang làm 1 bản cập nhật lớn có đăng nhập để fix lỗi thiếu chương này

Có đăng nhập nhưng vẫn bị anh ơi, hay là do metruyencv đòi phải nâng cấp TK ??? Anh xem thử nha, rất mong chờ bản nâng cấp của anh.

**Comment by nguyentd01** [comment]
Ý là cái phần mềm này của mình chỉ download truyện mà chưa đăng nhập tk á. Để mình thêm tính năng đăng nhập.

**Comment by nguyentd01** [comment]
Mà bạn bị thiếu nhiều chap không

**Comment by yeuemhon** [comment]
> Mà bạn bị thiếu nhiều chap không

Mình bị thiếu khoảng từ 10 đến 20 chap nhưng phân bố ngẫu nhiên á...

**Comment by nguyentd01** [comment]
Bạn tải bao nhiêu chap vậy

**Comment by yeuemhon** [comment]
> Bạn tải bao nhiêu chap vậy

Mình tải chỉ những truyện full, phần lớn thiếu chương ở cuối truyện (đôi khi ở chỗ khác), số chương tuỳ theo truyện khoảng từ 500 trở lên....cám ơn anh nhiều

**Comment by nguyentd01** [comment]
mình vừa đăng bản mới lên á.b test thử đi

**Comment by yeuemhon** [comment]
> mình vừa đăng bản mới lên á.b test thử đi

Bản mới thấy đã ổn rồi anh, thỉnh thoảng có bị nhảy chương hay bị báo UserWarning: Duplicate name... (do bản thân source của metruyencv bị lỗi) có thể sửa được bằng tay nên không sao, nếu anh save text của màn hình xủ lý ra log file lúc thoát ra để tiện theo dõi thì quá tốt, cám ơn anh rất nhiều và chúc anh thật may mắn.

**Comment by nguyentd01** [comment]
Mình vừa fix cái Duplicate name với tối ưu lại á.B xem thử đi
