### ISSUE TITLE
Lẫn lộn nội dung chương, thiếu text

### ISSUE THREAD

**Issue by phuongnullcare123** [nguyentd01/metruyencv_downloader#4]
Lẫn lộn tùm lum những vẫn rate 5*, căn bản dùng plw thì khó ăn nổi trang này. Bởi vì nó sẽ tạo ra 1 lớp canvas để che text 1 cách random. Các tốt nhât là bạn screenshot hết rồi đóng bớt bị lỗi hơn. :D. Mình dùng rồi nhé, dùng xong với reg acc voz cmt đấy. Hi vọng bản sau tốt hơn!

**Comment by nguyentd01** [comment]
Mình vừa đăng bản mới đó.B test thử đi

**Comment by yeuemhon** [comment]
> Lẫn lộn tùm lum những vẫn rate 5*, căn bản dùng plw thì khó ăn nổi trang này. Bởi vì nó sẽ tạo ra 1 lớp canvas để che text 1 cách random. Các tốt nhât là bạn screenshot hết rồi đóng bớt bị lỗi hơn. :D. Mình dùng rồi nhé, dùng xong với reg acc voz cmt đấy. Hi vọng bản sau tốt hơn!

Bạn thử down xong 01 truyện thì thoát ra chương trình, mỗi lần chỉ down 01 truyện thôi, không down liên tục nhé thì sẽ ổn (Không biết như vậy có phải là lỗi không...)

**Comment by yeuemhon** [comment]
> Mình vừa đăng bản mới đó.B test thử đi

Anh ơi, bản 1.1.1 bi lỗi ảnh, không sang text được rồi á...

**Comment by nguyentd01** [comment]
nó không chuyển sang text luôn hả b

**Comment by nguyentd01** [comment]
để mình check lại

**Comment by NTHieu002** [comment]
tool này dùng như thế nào vậy bạn ?

**Comment by nguyentd01** [comment]
Bạn tải bản exe về,điền tài khoản metruyencv với mật khẩu, chọn ổ đĩa, connection rồi paste link truyện (vd:https://metruyencv.info/truyen/cung-tien-tu-nhom-tro-choi ) và đợi nó tải về thôi.

**Comment by yeuemhon** [comment]
> để mình check lại

Hình như [metruyencv] lại chặn không cho down nữa rồi...

**Comment by hiameodom** [comment]
anh ơi, nó tải xong rồi nhưng vào chỗ lưu chỉ thấy để thư mục tên truyện chứ không có chứa dữ liệu truyện đã lưu ạ

**Comment by nguyentd01** [comment]
mình vừa fix r á.do metruyencv đổi tên miền thành metruyencv.info nên lỗi

**Comment by hiameodom** [comment]
cám ơn anh

**Comment by NTHieu002** [comment]
> Bạn tải bản exe về,điền tài khoản metruyencv với mật khẩu, chọn ổ đĩa, connection rồi paste link truyện (vd:https://metruyencv.info/truyen/cung-tien-tu-nhom-tro-choi ) và đợi nó tải về thôi.
bạn cho mình link file exe với, thật sự là chỉ thấy các file python thôi =))

**Comment by nguyentd01** [comment]
bạn tải file zip trong phần release r giải nén thôi

**Comment by phuongnullcare123** [comment]
Bản mới vẫn bị lộn text bạn ơi

**Comment by phuongnullcare123** [comment]
![Capture](https://github.com/user-attachments/assets/681ee539-1e77-419d-aea5-1ef6a85e5650)

**Comment by nguyentd01** [comment]
bạn dùng bản fast hay thường vậy

**Comment by phuongnullcare123** [comment]
> bạn dùng bản fast hay thường vậy

Bản mới nhất 1.1.2 đó bạn. Giờ cũng không tải được nữa 🗡️

**Comment by NTHieu002** [comment]
log tải xong mà folder empty này bạn =))) !!

**Comment by nguyentd01** [comment]
À bạn dùng link metruyencv.info là đc nhé.Dùng bản fast thử đi b

**Comment by phuongnullcare123** [comment]
> À bạn dùng link metruyencv.info là đc nhé.Dùng bản fast thử đi b

cả 2 bản luôn bạn. đang ngồi cap bằng selen rồi :D

**Comment by hiameodom** [comment]
em đang dùng bản 1,1,2 vẫn tải bình thường mà

**Comment by nguyentd01** [comment]
Để mình fix lỗi lại.Trước check thấy vẫn dùng ngon 😅

**Comment by duxonem** [comment]
Hình như metruyencv nó bỏ chuyển text thành canvas rồi hay sao đó

**Comment by nguyentd01** [comment]
có hả bạn, sao mình thấy vẫn v mà
