### ISSUE TITLE
Tiện làm luôn bachngocsach vip đi (bachngocsach.net.vn)

### ISSUE THREAD

**Issue by duxonem** [nguyentd01/metruyencv_downloader#5]

**Comment by nguyentd01** [comment]
oke để mình xem thử

**Comment by duxonem** [comment]
Bữa nhắn mà không thấy trả lời hoàn thiện của userscript này rồi. Có gì tham khảo thử cái của mình
https://greasyfork.org/vi/scripts/490097-bachngocsach-vip-scraper
